source "$HOME/.homesick/repos/homeshick/homeshick.sh"
fpath=($HOME/.homesick/repos/homeshick/completions $fpath)

DOTNET_CLI_TELEMETRY_OPTOUT=true

if [[ -e $HOME/.local/bin/ ]]; then
  export PATH=$HOME/.local/bin:$PATH;
fi

if [[ -e $HOME/.yarn/bin/ ]]; then
  export PATH=$HOME/.yarn/bin:$PATH;
fi

source $HOME/local/depot/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found


# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Additional completion definitions for Zsh
antigen bundle zsh-users/zsh-completions

# Load the theme.
antigen theme https://github.com/denysdovhan/spaceship-zsh-theme spaceship

# Tell Antigen that you're done.
antigen apply

if [[ -e $HOME/local/depot/gcloud/google-cloud-sdk ]]; then
    for f in $HOME/local/depot/gcloud/google-cloud-sdk/*.zsh.inc; do
        source $f;
    done
fi

if [[ -e $HOME/local/config/zsh ]]; then
  for f in $HOME/local/config/zsh/*.zsh; do
    source $f;
  done
fi

